service:
  name: test-ses
provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  memorySize: 128
  timeout: 10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource: "*"
functions:
  ktmb-2018:
    handler: index.handler
    events:
      - schedule: cron(* * * * ? *)
